// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerMetricsCore.Web.Data;

#nullable disable

namespace PokerMetricsCore.Web.Migrations
{
    [DbContext(typeof(PokerMetricsCoreContext))]
    partial class PokerMetricsCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PokerMetricsCore.Web.Models.Arquivo", b =>
                {
                    b.Property<int>("ArquivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataUploadUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeOriginalArquivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArquivoId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ARQUIVO", (string)null);
                });

            modelBuilder.Entity("PokerMetricsCore.Web.Models.DefinicaoTorneio", b =>
                {
                    b.Property<int>("DefinicaoTorneioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BuyIn")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<TimeOnly>("HorarioComeco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("DefinicaoTorneioId");

                    b.ToTable("DEFINICAO_TORNEIO", (string)null);

                    b.HasData(
                        new
                        {
                            DefinicaoTorneioId = 1,
                            BuyIn = 5.50m,
                            HorarioComeco = new TimeOnly(23, 34, 0),
                            Nome = "MICRO ROLLER"
                        },
                        new
                        {
                            DefinicaoTorneioId = 2,
                            BuyIn = 5.50m,
                            HorarioComeco = new TimeOnly(1, 54, 0),
                            Nome = "MICRO NIGHTLY"
                        },
                        new
                        {
                            DefinicaoTorneioId = 3,
                            BuyIn = 11.00m,
                            HorarioComeco = new TimeOnly(0, 20, 0),
                            Nome = "LUCKY 7s"
                        },
                        new
                        {
                            DefinicaoTorneioId = 4,
                            BuyIn = 11.00m,
                            HorarioComeco = new TimeOnly(14, 30, 0),
                            Nome = "CRAZY 8s"
                        },
                        new
                        {
                            DefinicaoTorneioId = 5,
                            BuyIn = 11.00m,
                            HorarioComeco = new TimeOnly(23, 10, 0),
                            Nome = "CRAZY KO"
                        },
                        new
                        {
                            DefinicaoTorneioId = 6,
                            BuyIn = 16.50m,
                            HorarioComeco = new TimeOnly(22, 34, 0),
                            Nome = "LOW ROLLER"
                        },
                        new
                        {
                            DefinicaoTorneioId = 7,
                            BuyIn = 16.50m,
                            HorarioComeco = new TimeOnly(2, 10, 0),
                            Nome = "CRAZY 8s MADRUGADA"
                        },
                        new
                        {
                            DefinicaoTorneioId = 8,
                            BuyIn = 9.90m,
                            HorarioComeco = new TimeOnly(3, 40, 0),
                            Nome = "MINOR NINER"
                        },
                        new
                        {
                            DefinicaoTorneioId = 9,
                            BuyIn = 9.90m,
                            HorarioComeco = new TimeOnly(15, 30, 0),
                            Nome = "EARLY NINER"
                        },
                        new
                        {
                            DefinicaoTorneioId = 10,
                            BuyIn = 4.40m,
                            HorarioComeco = new TimeOnly(1, 10, 0),
                            Nome = "MICRO MONSTER"
                        },
                        new
                        {
                            DefinicaoTorneioId = 11,
                            BuyIn = 55.00m,
                            HorarioComeco = new TimeOnly(2, 30, 0),
                            Nome = "NIGHTLY"
                        },
                        new
                        {
                            DefinicaoTorneioId = 12,
                            BuyIn = 0.00m,
                            HorarioComeco = new TimeOnly(0, 0, 0),
                            Nome = "FREEROLL"
                        });
                });

            modelBuilder.Entity("PokerMetricsCore.Web.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("PLAYER", (string)null);
                });

            modelBuilder.Entity("PokerMetricsCore.Web.Models.TorneioJogado", b =>
                {
                    b.Property<long>("TorneioJogadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataComeco")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefinicaoTorneioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NetResult")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalBuyIn")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalPayout")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("TorneioJogadoId");

                    b.HasIndex("DefinicaoTorneioId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReferenceId");

                    b.ToTable("TORNEIO_JOGADO", (string)null);
                });

            modelBuilder.Entity("PokerMetricsCore.Web.Models.Transacao", b =>
                {
                    b.Property<long>("TransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArquivoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Pontos")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorMonetario")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("TransacaoId");

                    b.HasIndex("ArquivoId");

                    b.ToTable("TRANSACAO", (string)null);
                });

            modelBuilder.Entity("PokerMetricsCore.Web.Models.Arquivo", b =>
                {
                    b.HasOne("PokerMetricsCore.Web.Models.Player", "Player")
                        .WithMany("Arquivos")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PokerMetricsCore.Web.Models.TorneioJogado", b =>
                {
                    b.HasOne("PokerMetricsCore.Web.Models.DefinicaoTorneio", "DefinicaoTorneio")
                        .WithMany()
                        .HasForeignKey("DefinicaoTorneioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokerMetricsCore.Web.Models.Player", "Player")
                        .WithMany("TorneiosJogados")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefinicaoTorneio");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PokerMetricsCore.Web.Models.Transacao", b =>
                {
                    b.HasOne("PokerMetricsCore.Web.Models.Arquivo", "Arquivo")
                        .WithMany("Transacoes")
                        .HasForeignKey("ArquivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arquivo");
                });

            modelBuilder.Entity("PokerMetricsCore.Web.Models.Arquivo", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("PokerMetricsCore.Web.Models.Player", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("TorneiosJogados");
                });
#pragma warning restore 612, 618
        }
    }
}
